framework:
  messenger:
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: async
          queues:
            async: ~
    routing:
      App\Message\AppointmentCreated: async
