apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-pwa-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: enterprise-pwa-api
  template:
    metadata:
      labels:
        app: enterprise-pwa-api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-pwa-api
spec:
  selector:
    app: enterprise-pwa-api
  ports:
    - port: 8000
      targetPort: 8000
